# version: "3"

# services:
#   builder:
#     image: node:18
#     build:
#       dockerfile: docker/Dockerfile
#       context: ./app
#     working_dir: /app

#   webapp:
#     image: nginx:stable-alpine
#     ports:
#       - "8080:8080"
#     networks:
#       - nginx-proxy-manager_default

# networks:
#   nginx-proxy-manager_default:
#     external: true

# version: "3"

# services:
#   builder:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: builder
#     working_dir: /app

#     command: sh -c "npm ci && npm run build"

#   thinkware:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: thinkware
#     ports:
#       - "8080:8080"
#     networks:
#       - nginx-proxy-manager_default

# networks:
#   nginx-proxy-manager_default:
#     external: true

version: "3"

services:
  thinkware_build_and_deploy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkware
    working_dir: /app

    ports:
      - "8080:8080"
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
