version: "3"

services:
  thinkware_build_and_deploy:
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkware
    working_dir: /app

    ports:
      - "8080:8080"
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
