version: "3"

services:
  thinkware_build_and_deploy:
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_NODE_ENV=${VITE_NODE_ENV}
      - VITE_KIRI_URL=${VITE_KIRI_URL}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkware
    working_dir: /app

    ports:
      - "8080:8080"
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
